/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import beans.veiculos.Automovel;
import beans.veiculos.Motocicleta;
import beans.veiculos.Van;
import beans.veiculos.VeiculoAbstract;
import beans.veiculos.atributos.Categoria;
import beans.veiculos.atributos.Estado;
import beans.veiculos.atributos.Marca;
import beans.veiculos.modelos.ModeloAutomovel;
import beans.veiculos.modelos.ModeloMotocicleta;
import beans.veiculos.modelos.ModeloVan;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author wande
 */
public class IncluirVeiculo extends javax.swing.JInternalFrame {

    private List<VeiculoAbstract> listaDeVeiculos;

    public IncluirVeiculo(List<VeiculoAbstract> listaDeVeiculos) {
        initComponents();
        this.listaDeVeiculos = listaDeVeiculos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxMarca = new javax.swing.JComboBox<>();
        boxCategoria = new javax.swing.JComboBox<>();
        boxModelo = new javax.swing.JComboBox<>();
        boxEstado = new javax.swing.JComboBox<>();
        boxTipo = new javax.swing.JComboBox<>();
        boxValorDeCompra = new javax.swing.JFormattedTextField();
        boxPlaca = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaoIncluir = new javax.swing.JButton();
        boxAno = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Incluir Veículo");

        boxMarca.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Marca.values()));
        boxMarca.setSelectedItem(null);

        boxCategoria.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Categoria.values()));
        boxCategoria.setSelectedItem(null);

        boxEstado.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Estado.values()));
        boxEstado.setSelectedItem(null);
        boxEstado.setToolTipText("");

        boxTipo.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Tipo.values()));
        boxTipo.setSelectedItem(null);
        boxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                changeTipo(evt);
            }
        });

        boxValorDeCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        boxValorDeCompra.setText("R$ ");

        try {
            boxPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU'-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setLabelFor(boxMarca);
        jLabel1.setText("Marca:");

        jLabel2.setLabelFor(boxEstado);
        jLabel2.setText("Estado:");

        jLabel3.setLabelFor(boxCategoria);
        jLabel3.setText("Categoria:");

        jLabel4.setLabelFor(boxTipo);
        jLabel4.setText("Tipo:");

        jLabel5.setLabelFor(boxModelo);
        jLabel5.setText("Modelo:");

        jLabel6.setLabelFor(boxValorDeCompra);
        jLabel6.setText("Valor de Compra:");

        jLabel7.setLabelFor(boxPlaca);
        jLabel7.setText("Placa:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Insira as informações do veículo:");

        botaoIncluir.setText("Incluir");
        botaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoIncluirMouseReleased(evt);
            }
        });

        try {
            boxAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Ano de Compra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(boxMarca, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxEstado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxPlaca)
                        .addComponent(boxValorDeCompra))
                    .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxValorDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botaoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeTipo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_changeTipo
        switch (boxTipo.getSelectedIndex()) {
            case (0):
                boxModelo.setModel(new DefaultComboBoxModel(ModeloAutomovel.values()));
                break;
            case (1):
                boxModelo.setModel(new DefaultComboBoxModel(ModeloMotocicleta.values()));
                break;
            case (2):
                boxModelo.setModel(new DefaultComboBoxModel(ModeloVan.values()));
                break;
        }
        boxModelo.setSelectedItem(null);
    }//GEN-LAST:event_changeTipo

    private void botaoIncluirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIncluirMouseReleased
        if (boxCategoria.getSelectedIndex() < 0 || boxEstado.getSelectedIndex() < 0 || boxMarca.getSelectedIndex() < 0) {
            Dialog.main("Um ou mais campos enocontram-se vazios.");
            return;
        }

        if (boxTipo.getSelectedIndex() < 0 || boxPlaca.getText().length() < 7 || (Long) boxValorDeCompra.getValue() < 0 || boxModelo.getSelectedIndex() < 0) {
            Dialog.main("Um ou mais campos enocontram-se vazios.");
            return;
        }

        if (Integer.parseInt(boxAno.getText()) < 1900) {
            Dialog.main("O ano é inferior a 1900.");
            return;
        }

        Categoria categoria = (Categoria) boxCategoria.getSelectedItem();
        Estado estado = (Estado) boxEstado.getSelectedItem();
        Marca marca = (Marca) boxMarca.getSelectedItem();
        double valorDeCompra = ((Long) boxValorDeCompra.getValue()).doubleValue();
        String placa = boxPlaca.getText();
        int ano = Integer.parseInt(boxAno.getText());
        VeiculoAbstract novoVeiculo = null;
        switch (boxTipo.getSelectedIndex()) {
            case (0):
                ModeloAutomovel modeloAuto = (ModeloAutomovel) boxModelo.getSelectedItem();
                novoVeiculo = new Automovel(modeloAuto, estado, marca, categoria, placa, ano, valorDeCompra);
                break;
            case (1):
                ModeloMotocicleta modeloMoto = (ModeloMotocicleta) boxModelo.getSelectedItem();
                novoVeiculo = new Motocicleta(modeloMoto, estado, marca, categoria, placa, ano, valorDeCompra);
                break;
            case (2):
                ModeloVan modeloVan = (ModeloVan) boxModelo.getSelectedItem();
                novoVeiculo = new Van(modeloVan, estado, marca, categoria, placa, ano, valorDeCompra);
                break;
        }
        if (novoVeiculo != null) {
            this.listaDeVeiculos.add(novoVeiculo);
            boxEstado.setSelectedIndex(-1);
            boxMarca.setSelectedIndex(-1);
            boxTipo.setSelectedIndex(-1);
            boxCategoria.setSelectedIndex(-1);
            boxPlaca.setText("");
            boxAno.setText("");
            boxValorDeCompra.setText("");
            Dialog.main("Veículo de placa " + placa + " cadastrado com sucesso!");
        }
    }//GEN-LAST:event_botaoIncluirMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JFormattedTextField boxAno;
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JComboBox<String> boxMarca;
    private javax.swing.JComboBox<String> boxModelo;
    private javax.swing.JFormattedTextField boxPlaca;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JFormattedTextField boxValorDeCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
