package views;

import beans.veiculos.Automovel;
import beans.veiculos.Motocicleta;
import beans.veiculos.Van;
import beans.veiculos.VeiculoAbstract;
import beans.veiculos.TabelaVenda;
import beans.veiculos.atributos.Categoria;
import beans.veiculos.atributos.Estado;
import beans.veiculos.atributos.Marca;
import beans.veiculos.atributos.Tipo;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

public class VenderVeiculo extends javax.swing.JInternalFrame {

    private final TabelaVenda tabelaVenda = new TabelaVenda();
    private final List<VeiculoAbstract> listaDeVeiculos;
    private int linhaAtual = -1;
    
    public VenderVeiculo(List<VeiculoAbstract> listaDeVeiculos) {
       this.listaDeVeiculos = listaDeVeiculos;

        initComponents();
        TabelaVenda.getColumnModel().getColumn(0).setPreferredWidth(20);
        gerarNovosResultados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        filtroTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        filtroMarca = new javax.swing.JComboBox<>();
        filtroMarcaIncluir = new javax.swing.JCheckBox();
        filtroTipoIncluir = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        filtroCategoria = new javax.swing.JComboBox<>();
        filtroCategoriaIncluir = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        selectedRow = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botaoVender = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vender Veiculo");
        setMinimumSize(new java.awt.Dimension(108, 40));
        setPreferredSize(new java.awt.Dimension(1151, 645));

        TabelaVenda.setModel(tabelaVenda);
        TabelaVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaVendaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaVenda);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar Veículo"));

        filtroTipo.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Tipo.values()));
        filtroTipo.setSelectedItem(null);
        filtroTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroTipoItemStateChanged(evt);
            }
        });
        filtroTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo:");

        filtroMarca.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Marca.values()));
        filtroMarca.setSelectedItem(null);
        filtroMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroMarcaItemStateChanged(evt);
            }
        });

        filtroMarcaIncluir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroMarcaIncluirItemStateChanged(evt);
            }
        });

        filtroTipoIncluir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroTipoIncluirItemStateChanged(evt);
            }
        });

        jLabel5.setText("Marca:");

        filtroCategoria.setModel(new DefaultComboBoxModel(beans.veiculos.atributos.Categoria.values()));
        filtroCategoria.setSelectedItem(null);
        filtroCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroCategoriaItemStateChanged(evt);
            }
        });

        filtroCategoriaIncluir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroCategoriaIncluirItemStateChanged(evt);
            }
        });

        jLabel6.setText("Categoria:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtroTipoIncluir)
                    .addComponent(filtroMarcaIncluir)
                    .addComponent(filtroCategoriaIncluir))
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(filtroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(filtroTipoIncluir))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(filtroMarcaIncluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filtroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(filtroCategoriaIncluir))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Veículo selecionado:");

        botaoVender.setText("Vender");
        botaoVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoVenderMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(selectedRow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botaoVender))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(selectedRow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(botaoVender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaVendaMousePressed
        linhaAtual = TabelaVenda.rowAtPoint(evt.getPoint());
        if (linhaAtual != -1) {
            selectedRow.setText(String.valueOf(linhaAtual));
        }
    }//GEN-LAST:event_TabelaVendaMousePressed

    private void filtroTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroTipoItemStateChanged
        filtroTipoIncluir.setSelected(true);
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroTipoItemStateChanged

    private void filtroTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTipoActionPerformed

    private void filtroMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroMarcaItemStateChanged
        filtroMarcaIncluir.setSelected(true);
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroMarcaItemStateChanged

    private void filtroMarcaIncluirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroMarcaIncluirItemStateChanged
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroMarcaIncluirItemStateChanged

    private void filtroTipoIncluirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroTipoIncluirItemStateChanged
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroTipoIncluirItemStateChanged

    private void filtroCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroCategoriaItemStateChanged
        this.filtroCategoriaIncluir.setSelected(true);
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroCategoriaItemStateChanged

    private void filtroCategoriaIncluirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroCategoriaIncluirItemStateChanged
        this.gerarNovosResultados();
    }//GEN-LAST:event_filtroCategoriaIncluirItemStateChanged

    private void botaoVenderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVenderMouseReleased
        if (linhaAtual < 0) {
            Dialog.main("O veículo não foi selecionado");
            return;
        }
        VeiculoAbstract veiculo = tabelaVenda.getVeiculo(linhaAtual);
        veiculo.vender();
        this.gerarNovosResultados();
        Dialog.main("O veículo de placa " + veiculo.getPlaca() + " foi vendido com sucesso!");
    }//GEN-LAST:event_botaoVenderMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaVenda;
    private javax.swing.JButton botaoVender;
    private javax.swing.JComboBox<String> filtroCategoria;
    private javax.swing.JCheckBox filtroCategoriaIncluir;
    private javax.swing.JComboBox<String> filtroMarca;
    private javax.swing.JCheckBox filtroMarcaIncluir;
    private javax.swing.JComboBox<String> filtroTipo;
    private javax.swing.JCheckBox filtroTipoIncluir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectedRow;
    // End of variables declaration//GEN-END:variables


    private void gerarNovosResultados() {
        Iterator<VeiculoAbstract> i;
        List<VeiculoAbstract> veiculosFiltrados = new ArrayList<>();

        listaDeVeiculos.forEach(e -> {
            if (e.getEstado() == (Estado) Estado.DISPONIVEL) {
                veiculosFiltrados.add(e);
            }
        });

        if (filtroTipoIncluir.isSelected() && filtroTipo.getSelectedIndex() > -1) {
            i = veiculosFiltrados.iterator();
            while (i.hasNext()) {
                VeiculoAbstract veiculo = i.next();
                switch ((Tipo) filtroTipo.getSelectedItem()) {
                    case AUTOMOVEL:
                        if (!(veiculo instanceof Automovel)) {
                            i.remove();
                        }
                        break;
                    case MOTOCICLETA:
                        if (!(veiculo instanceof Motocicleta)) {
                            i.remove();
                        }
                        break;
                    case VAN:
                        if (!(veiculo instanceof Van)) {
                            i.remove();
                        }
                        break;
                }
            }
        }

        if (filtroMarcaIncluir.isSelected() && filtroMarca.getSelectedIndex() > -1) {
            i = veiculosFiltrados.iterator();
            while (i.hasNext()) {
                VeiculoAbstract veiculo = i.next();
                if (veiculo.getMarca() != (Marca) filtroMarca.getSelectedItem()) {
                    i.remove();
                }
            }
        }

        if (filtroCategoriaIncluir.isSelected() && filtroCategoria.getSelectedIndex() > -1) {
            i = veiculosFiltrados.iterator();
            while (i.hasNext()) {
                VeiculoAbstract veiculo = i.next();
                if (veiculo.getCategoria() != (Categoria) filtroCategoria.getSelectedItem()) {
                    i.remove();
                }
            }
        }

        this.tabelaVenda.refreshTabela(veiculosFiltrados);
        selectedRow.setText("");
        linhaAtual = -1;
    }

}
